suzuki-shunsuke/tfaction

docs/config.md
list-targets-with-changed-files/dist/index.js
list-targets-with-changed-files/src/index.ts

feat: make label_prefixes optional

---

docs/add-working-directory.md

https://github.com/suzuki-shunsuke/terraform-aws-tfaction

docs: add a link to terraform-aws-tfaction

---

get-target-config/README.md
get-target-config/action.yaml
get-target-config/dist/index.js
get-target-config/src/index.ts
setup/action.yaml

feat: support GCP

---

create-scaffold-pr/action.yaml

Draft Pull Request isn't available in some condition, so it isn't appropriate as default setting.

fix: disable draft pr by default (create-scaffold-pr)

---

README.md
docs/config.md
list-targets-with-changed-files/dist/index.js
list-targets-with-changed-files/src/index.ts

feat: support environment

---

.github/workflows/test-get-target-config.yaml
docs/config.md
get-global-config/tests/config-1.yaml
get-target-config/dist/index.js
get-target-config/src/index.ts
get-target-config/src/lib.ts
get-target-config/tests/config-1.yaml

feat: change configuration structure

---

docs/config.md
export-secrets/dist/index.js
export-secrets/src/index.ts
export-secrets/src/lib.ts
get-global-config/tests/config-1.yaml
get-target-config/dist/index.js
get-target-config/src/index.ts
get-target-config/src/lib.ts
get-target-config/tests/config-1.yaml
list-targets-with-changed-files/dist/index.js
list-targets-with-changed-files/src/index.ts
list-targets-with-changed-files/src/lib.ts

BREAKING CHANGE: configuration field `targets` was renamed

feat: rename targets to target_groups

---

export-aws-secrets-manager/dist/index.js
export-aws-secrets-manager/src/run.ts

https://github.com/actions/toolkit/tree/main/packages/core#setting-a-secret
Follow up #112

fix(export-aws-secrets-manager): mask secrets

---

test/action.yaml

* https://github.com/suzuki-shunsuke/github-action-tfsec/releases/tag/v0.1.3
* https://github.com/suzuki-shunsuke/github-action-tflint/releases/tag/v0.1.2
Change Reviewdog format from checkstyle to [Reviewdog Diagnostic Format](https://github.com/reviewdog/reviewdog#reviewdog-diagnostic-format-rdformat)

chore: update tfsec and tflint

---

create-scaffold-pr/action.yaml

Fix the error
```
Run suzuki-shunsuke/tfaction/get-target-config@v0.4.0
Error: "environment variable TFACTION_JOB_TYPE is required"
```

fix(create-scaffold-pr): set TFACTION_JOB_TYPE

---

docs/config.md
get-target-config/dist/index.js
get-target-config/src/index.ts
get-target-config/src/lib.ts
get-target-config/tests/aws/foo/tfaction.yaml
get-target-config/tests/config-1.yaml

feat(get-target-config): support configurating tfaction by tfaction.yaml

---

export-secrets/README.md

This PR is related to #132. Please confirm this.

docs: Add required parameter in document of export-secrets

---

terraform-apply/action.yaml
terraform-plan/action.yaml
tfmigrate-plan/action.yaml

Reverts suzuki-shunsuke/tfaction#140

Revert "fix: specify AWS_DEFAULT_REGION"

---

create-scaffold-pr/action.yaml
get-target-config/dist/index.js
get-target-config/src/index.ts
get-target-config/src/lib.ts
scaffold-working-dir/action.yaml

```
Error: ENOENT: no such file or directory, open 'github/foo/tfaction.yaml'
```
Due to #128
Affected version: v0.4.4 v0.4.5 v0.4.6

fix(scaffold-working-dir): fix the error of get-target-config

---

get-target-config/dist/index.js
get-target-config/src/index.ts

#144
Follow up #143
Fix error (scaffold-working-dir)
```
"unknown type: scaffold_working_dir"
```

fix(get-target-config): support scaffold-working-dir

---

get-target-config/dist/index.js
get-target-config/src/index.ts

```
Error: "unknown type: scaffold_working_dir"
```

fix: fix scaffold-working-dir

---

terraform-plan/main.sh

```
Error: running test: load: loading policies: load: 1 error occurred during loading: stat /home/runner/work/test-tfaction-getting-started/test-tfaction-getting-started/policy: no such file or directory
```

fix: skip conftest if policy isn't found

---

terraform-plan/action.yaml

fix: fix parse error

---

.github/workflows/apply.yaml
.github/workflows/scaffold-working-directory.yaml
.github/workflows/test.yaml
setup/action.yaml

Fix the error
```
time="2022-02-08T04:08:26Z" level=fatal msg="get a pull request: GET https://api.github.com/repos/suzuki-shunsuke/terraform-monorepo-github-actions/pulls/284: 401 Bad credentials []"
github-comment error: failed to create an issue comment: send a comment by GitHub API: status code: 401, {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}: status code >= 300
run a command: exit status 1
Error: Process completed with exit code 1.
```

fix: set GITHUB_TOKEN

---

terraform-apply/action.yaml

fix(terraform-apply): fix if condition

---

setup/action.yaml

fix: fix typo

---

check-terraform-skip/dist/index.js
check-terraform-skip/src/index.ts

fix: change the default behavior to keep the compatibility

---

list-targets/README.md

docs(list-targets): update document

---

test/action.yaml

https://github.com/suzuki-shunsuke/github-action-tflint/releases/tag/v0.1.3-0

feat: update tflint action to notify with github-comment

---

test/action.yaml

https://github.com/suzuki-shunsuke/github-action-tfsec/releases/tag/v0.1.4-0

feat: update tfsec action to notify with github-comment

---

schema/tfaction-root.json

Follow up https://github.com/suzuki-shunsuke/tfaction/pull/153

docs: update JSON Schema

---

create-scaffold-pr/action.yaml

feat(create-scaffold-pr): add mention to GITHUB_ACTOR

---

scaffold-tfmigrate/action.yaml
scaffold-tfmigrate/migration.hcl
scaffold-tfmigrate/tfmigrate.hcl

feat: scaffold-tfmigrate

---

scaffold-tfmigrate/action.yaml

fix: fix scaffold .tfmigrate.hcl

---

terraform-apply/action.yaml
terraform-plan/action.yaml

fix: rename output

---

create-follow-up-pr/action.yaml
create-follow-up-pr/github-comment.yaml
create-follow-up-pr/skip_create_pr.sh
create-scaffold-pr/action.yaml
get-global-config/action.yaml
get-global-config/dist/index.js
get-global-config/src/index.ts
scaffold-tfmigrate/action.yaml

#202
Changed actions
* create-follow-up-pr
* create-scaffold-pr
* scaffold-tfmigrate
* get-global-config
`skip_create_pr` is added to `tfaction-root.yaml`.

feat: support skipping to create pull requests

---

create-follow-up-pr/skip_create_pr.sh
create-scaffold-pr/action.yaml
scaffold-tfmigrate/action.yaml
scaffold-working-dir/action.yaml

fix: set "-R $GITHUB_REPOSITORY"

---

create-follow-up-pr/action.yaml
create-follow-up-pr/skip_create_pr.sh
scaffold-tfmigrate/action.yaml

fix: set tfmigrate label and target label

---

create-follow-up-pr/github-comment.yaml

feat: improve the follow up pull request guide

---

list-targets/action.yaml
setup/action.yaml

Reduce the number of GitHub API call by ci-info

feat: upload and download ci-info's output

---

list-targets/action.yaml

fix: fix step id

---

list-targets/action.yaml
setup/action.yaml

fix: upload and download CI_INFO_TEMP_DIR

---

test-module/action.yaml

feat: generate document by terraform-docs

---

test-module/action.yaml

fix: fix terraform-docs step

---

scaffold-module/action.yaml

fix: run aqua init

---

release-module/action.yaml

fix: set `shell: bash`

---

release-module/action.yaml

feat(release-module): add release note

---

scaffold-tfmigrate/action.yaml

fix(scaffold-tfmigrate): create tfmigrate label

---

scaffold-tfmigrate/action.yaml

fix: add newline

---

terraform-plan/main.sh
tfmigrate-plan/main.sh

fix: Delete old plan file in GCS when terraform plan fails

---

create-follow-up-pr/action.yaml
create-scaffold-pr/action.yaml
scaffold-module/action.yaml
scaffold-tfmigrate/action.yaml

close #256 and fixed other condition that is same as the issue.

fix: Change condition to compare with string

---

create-follow-up-pr/action.yaml
create-scaffold-pr/action.yaml
scaffold-module/action.yaml
scaffold-tfmigrate/action.yaml

fix: Modify condition to campare with fromJSON

---

test-module/action.yaml
test/action.yaml

https://github.com/suzuki-shunsuke/github-action-tfsec/releases/tag/v0.1.6
https://github.com/suzuki-shunsuke/github-action-tfsec/pull/92

fix: update tfsec action

---

test-module/action.yaml
test/action.yaml

https://github.com/suzuki-shunsuke/github-action-tfsec/releases/tag/v0.1.7

chore: update tfsec action

---

get-target-config/dist/index.js
get-target-config/package-lock.json
get-target-config/package.json
get-target-config/src/index.ts
get-target-config/src/lib.ts

Support the environment variable `TFACTION_WORKING_DIR` instead of `TFACTION_TARGET`.
In some usecases, working directory is more user friendly than target.
```yaml
name: Scaffold a working directory
on:
workflow_dispatch:
inputs:
working_dir:
description: 'working directory'
required: true
env:
TFACTION_WORKING_DIR: ${{github.event.inputs.working_dir}}
jobs:
scaffold:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: ./.github/actions/aqua
- uses: suzuki-shunsuke/tfaction/scaffold-working-dir@main
id: scaffold-working-dir
```

feat(scaffold-working-dir): support TFACTION_WORKING_DIR

---

get-target-config/dist/index.js
get-target-config/src/index.ts
get-target-config/src/lib.ts

feat: support setting environment variable

---

create-follow-up-pr/github-comment.yaml
create-follow-up-pr/main.sh
create-follow-up-pr/skip_create_pr.sh
terraform-plan/github-comment.yaml
terraform-plan/main.sh
tfmigrate-apply/github-comment.yaml
tfmigrate-apply/main.sh
tfmigrate-plan/github-comment.yaml
tfmigrate-plan/main.sh

https://github.com/suzuki-shunsuke/github-comment/pull/515

fix: replace github-comment env function to var option to support github-comment v5

---

get-target-config/action.yaml
setup/action.yaml

Thanks for sharing tfaction, it really helps me to keep troubles away from my daily job. :)
I just found typos in the description of actions, so let me send a PR to fix them. Please have a look when your time permits. Thanks in advance!

Fix typo in the description

---

create-scaffold-pr/action.yaml
scaffold-module/action.yaml
scaffold-tfmigrate/action.yaml

https://github.com/suzuki-shunsuke/tfaction/issues/499

feat: replace annotation to $GITHUB_STEP_SUMMARY for creating pull requests

---

create-follow-up-pr/main.sh
create-follow-up-pr/skip_create_pr.sh
create-scaffold-pr/action.yaml
release-module/action.yaml
scaffold-module/action.yaml
scaffold-tfmigrate/action.yaml

https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
> GITHUB_SERVER_URL	The URL of the GitHub server. For example: https://github.com.

fix: use GITHUB_SERVER_URL

---

.github/workflows/create-pr-branch.yaml
check-terraform-skip/dist/LICENSE
check-terraform-skip/dist/index.js
create-scaffold-pr/action.yaml
export-aws-secrets-manager/dist/LICENSE
export-aws-secrets-manager/dist/index.js
export-aws-secrets-manager/package-lock.json
export-secrets/dist/LICENSE
export-secrets/dist/index.js
get-global-config/dist/LICENSE
get-global-config/dist/index.js
get-target-config/dist/LICENSE
get-target-config/dist/index.js
get-target-config/package-lock.json
list-changed-modules/dist/LICENSE
list-changed-modules/dist/index.js
list-targets-with-changed-files/dist/LICENSE
list-targets-with-changed-files/dist/index.js
list-targets-with-changed-files/package-lock.json
list-working-dirs/action.yaml
release-module/action.yaml
scaffold-module/action.yaml
scaffold-tfmigrate/action.yaml
setup/action.yaml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

fix: use GITHUB_OUTPUT instead of deprecated set-output command

---

.github/workflows/actionlint.yaml
.github/workflows/apply.yaml
.github/workflows/create-pr-branch.yaml
.github/workflows/deploy-schema.yaml
.github/workflows/prerelease-pr.yaml
.github/workflows/release.yaml
.github/workflows/renovate-config-validator.yaml
.github/workflows/scaffold-working-directory.yaml
.github/workflows/test-get-target-config.yaml
.github/workflows/test-list-working-dirs.yaml
.github/workflows/test.yaml
terraform-plan/action.yaml

`terraform-plan`: The input `github_app_token` is removed.
Please replace `github_app_token` to `github_token`.

refactor(terraform-plan): remove an unused input `github_app_token`

---

get-global-config/dist/index.js
get-global-config/src/index.ts
terraform-apply/action.yaml
terraform-apply/main.sh
tfmigrate-apply/action.yaml
tfmigrate-apply/main.sh

- https://github.com/suzuki-shunsuke/tfaction/issues/892
```yaml
update_related_pull_requests:
enabled: false
```
By default, this feature is enabled.

feat: support disabling to update related pull requests

---

get-global-config/action.yaml
get-global-config/dist/index.js
get-global-config/src/index.ts
get-target-config/action.yaml
test-module/action.yaml

feat(test-module): support trivy and disabling linters tflint, tfsec, and trivy

---

update-drift-issue/action.yaml
update-drift-issue/github-comment.yaml
update-drift-issue/post-comment.sh

- https://github.com/suzuki-shunsuke/tfaction/discussions/983
Updated `update-drift-issue` action to post a comment if CI failed and no comment was posted.

feat(update-drift-issue): post a comment if CI failed and no comment was posted

---

update-drift-issue/action.yaml

fix(update-drift-issue): set TFACTION_DRIFT_ISSUE_REPO_OWNER and TFACTION_DRIFT_ISSUE_REPO_NAME

---

get-global-config/dist/index.js
get-global-config/src/index.ts

fix(get-global-config): disable aqua_update_checksum_skip_push if TFACTION_DRIFT_ISSUE_NUMBER is set

---

get-global-config/dist/index.js
get-global-config/src/index.ts
setup/action.yaml

- https://github.com/aquaproj/update-checksum-action/pull/39

fix(setup): update update-checksum action

---

get-target-config/src/index.ts
setup/action.yaml

Close https://github.com/suzuki-shunsuke/tfaction/issues/1228

feat(setup): support pull_request_target

---

test/action.yaml

- https://github.com/suzuki-shunsuke/github-action-tflint/pull/683
- https://github.com/suzuki-shunsuke/github-action-tfsec/pull/658
- https://github.com/suzuki-shunsuke/trivy-config-action/pull/48
This bug was caused by the bug of reviewdog.
- https://github.com/reviewdog/reviewdog/issues/1408

fix(test): Fix a bug that test succeeds even if tflint, trivy, and tfsec fail

---

test-module/action.yaml

- https://github.com/suzuki-shunsuke/tfaction/pull/1242

fix(test-module): update tflint and tfsec action

---

terraform-apply/main.sh
tfmigrate-apply/github-comment.yaml
tfmigrate-apply/main.sh

Close #902
Pull Requests with the label `tfaction:disable-auto-update` aren't updated.

feat: support disabling to update related pull requests per pull request by pull request label

---

README.md

- https://github.com/suzuki-shunsuke/tfaction/discussions/1280

docs: add the section "Who uses tfaction?"

---

README.md

Hello 👋, I'll propose this PR to list our usecase in the `README.md`
We have not created blog post for now, so added a link to the release we've contributed.
Thanks for your maintenance!

Add Henry, Inc. to the list of usecases

---

README.md

Hello👋 Thank you for publishing your great product!
I'm @ism-k from Macbee Planet Inc. (https://macbee-planet.com). We use tfaction in our company and we are driving improvements in the DevOps side of our business with tfaction as our main focus. We would love to add our name to this list.

docs: Add Macbee Planet Inc. to who-uses-tfaction

---

README.md

Hi, I'm @johnmanjiro13 from [Gunosy Inc.](https://gunosy.co.jp).
First, Thank you for your product. It's really useful for us on a daily basis.
We use tfaction in almost all of products, and we are attracted by the affinity with GitHub Actions and the safety by Terraform Plan file.
We would be happy to add our company name to the list!

docs: Add Gunosy Inc. to who-uses-tfaction

---

get-target-config/action.yaml
get-target-config/dist/index.js
get-target-config/src/index.ts
get-target-config/src/lib.ts
terraform-plan/action.yaml
terraform-plan/main.sh
test/action.yaml

Support destroying resources with `terraform plan`'s `-destroy` option.
If you want to destroy all resources, please set `destroy: true` in `tfaction.yaml`.
tfaction.yaml
```yaml
destroy: true
```

feat: support running `terraform plan` with the `-destroy` option

---

README.md

Hello, I'm an employee of Luup, Inc.
First, thanks for creating such a tool. It has been instrumental in our day-to-day development.
We use tfaction for the management of almost all resources (non-automatically generated resources ). We would appreciate it if you could include our company name in the list.

docs: Add Luup, Inc. to who-uses-tfaction

---

README.md

Hi, I’m @irotoris from Wantedly, Inc.
Thank you for your great products! We use tfaction in the management of all our cloud infrastructure.
I would be happy if you could add our company name to the who-uses list!

docs: Add Wantedly, Inc. to who-uses-tfaction

---

release-module/action.yaml

fix(release-module): replace all slash to _

---

test/action.yaml

Fix a bug that auto format by `terraform fmt` doesn't work on other than `pull_request` event.
https://suzuki-shunsuke.github.io/tfaction/docs/feature/auto-fix

fix: fix a bug that Terraform configuration isn't formatted automatically on other than pull_request event

---

check-terraform-skip/package-lock.json
check-terraform-skip/package.json
export-aws-secrets-manager/package-lock.json
export-aws-secrets-manager/package.json
export-secrets/package-lock.json
export-secrets/package.json
get-global-config/package-lock.json
get-global-config/package.json
get-target-config/package-lock.json
get-target-config/package.json
list-changed-modules/package-lock.json
list-changed-modules/package.json
list-targets-with-changed-files/package-lock.json
list-targets-with-changed-files/package.json

Reverts suzuki-shunsuke/tfaction#1481
To resolve the conflict. https://github.com/suzuki-shunsuke/tfaction/pull/1479

Revert "fix(deps): update dependency @types/node to v20.11.8"

---

check-terraform-skip/package-lock.json
check-terraform-skip/package.json
export-aws-secrets-manager/package-lock.json
export-aws-secrets-manager/package.json
export-secrets/package-lock.json
export-secrets/package.json
get-global-config/package-lock.json
get-global-config/package.json
get-target-config/package-lock.json
get-target-config/package.json
list-changed-modules/package-lock.json
list-changed-modules/package.json
list-targets-with-changed-files/package-lock.json
list-targets-with-changed-files/package.json

Reverts suzuki-shunsuke/tfaction#1483

Revert "fix(deps): update dependency @types/node to v20.11.9"

---

renovate.json5

- https://github.com/suzuki-shunsuke/tfaction/pull/1479

chore(renovate): disable npm update until #1479 is merged

---

test-module/action.yaml

fix(test-module): run `terraform init` to install dependent providers and modules

---

test-module/action.yaml

- https://github.com/suzuki-shunsuke/tfaction/issues/1582#issuecomment-1993912111

fix(test-module): support pull_request_target

---

terraform-apply/download_plan_file.sh
terraform-apply/github-comment.yaml

fix(terraform-apply): output the good error message if plan_workflow_name is wrong

---

.github/workflows/prerelease-pr.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
.github/workflows/watch-star.yaml
.github/workflows/wc-create-pr-branch.yaml
.github/workflows/wc-deploy-schema.yaml
.github/workflows/wc-enable-auto-merge.yaml
.github/workflows/wc-ghalint.yaml
.github/workflows/wc-prettier.yaml
.github/workflows/wc-test-get-target-config.yaml
.github/workflows/wc-test-list-working-dirs.yaml
aqua-checksums.json

https://github.com/suzuki-shunsuke/batch-bulk-ghatm/issues/1

ci: set timeout-minutes using ghatm

---

list-working-dirs/action.yaml
scaffold-tfmigrate/action.yaml

Fix bugs to support GitHub Enterprise Server

refactor: refactor context values

---

conftest/dist/index.js
conftest/src/run.ts

- https://github.com/suzuki-shunsuke/tfaction/issues/1896#issuecomment-2410985416

fix(conftest): fix a bug that conftest -data option is wrong

---

test-module/action.yaml

fix(test-module): stop running Conftest in test-module for now

---

.github/workflows/release.yaml

Fix the failure.
https://github.com/suzuki-shunsuke/tfaction/actions/runs/11368001447/job/31622027951

ci(release): install aqua always

---

get-target-config/src/run.ts
get-target-config/tsconfig.json

feat(get-target-config): improve the default session name

---

terraform-plan/action.yaml

fix(terraform-plan): skip conftest if skip label is set

---

list-changed-modules/action.yaml
list-module-callers/action.yaml
list-module-callers/src/index.ts
list-module-callers/src/lib.ts
list-targets-with-changed-files/action.yaml
list-targets-with-changed-files/src/run.ts
list-targets/action.yaml

fix(list-targets): fix resolving module dependencies

---

test-module/action.yaml
test/action.yaml

chore: update github-action-tflint to support tflint v0.54.0 or later

---

get-target-config/src/run.ts
lib/src/index.ts
test/action.yaml

Close #1892
This feature is enabled by default.
If you want to disable this, please do it by tfaction-root.yaml:
```yaml
tflint:
enabled: true
fix: false # Disable tflint --fix
```

feat(test): support tflint --fix

---

README.md

Hi!
We are using tfaction to automate our terraform workflow.
We have written an article about the process of adopting tfaction and how to implement it, and would be happy to include it in our README!
Thank you so much for the great features you provide!
- Link to the issue:

docs: add tacoms to who-uses-tfaction

---

terraform-plan/main.sh

- Link to the issue: https://github.com/suzuki-shunsuke/tfaction/issues/2132

Fix tfplan file path issue when using Terragrunt

---

test-module/action.yaml
test/action.yaml

- https://github.com/suzuki-shunsuke/github-action-tflint/pull/1211
- https://github.com/suzuki-shunsuke/github-action-tflint/releases/tag/v1.2.1

chore: update github-action-tflint to v1.2.1

---

.github/workflows/wc-create-pr-branch.yaml
test/action.yaml

- Before: 2m18s https://github.com/suzuki-shunsuke/tfaction/actions/runs/12451476906
- After: 1m30s https://github.com/suzuki-shunsuke/tfaction/actions/runs/12453647737?pr=2138

ci: split jobs

---

.github/workflows/main.yaml
.github/workflows/release.yaml
.github/workflows/wc-create-pr-branch.yaml
.github/workflows/wc-deploy-schema.yaml
.github/workflows/wc-format.yaml
.github/workflows/wc-ghalint.yaml
.github/workflows/wc-hide-comment.yaml
.github/workflows/wc-shellcheck.yaml
.github/workflows/wc-test.yaml

https://github.com/suzuki-shunsuke/batch-bulk-disable-checkout-persist-credentials/issues/1

ci: disable actions/checkout's persist-credentials using disable-checkout-persist-credentials

---

get-global-config/action.yaml
js/action.yaml
js/src/get-global-config/index.test.ts
js/src/get-global-config/index.ts
js/src/test-action/index.ts
test-module/action.yaml

Close #2175
- If tflint's fix is true, code is fixed properly https://github.com/suzuki-shunsuke/test-tfaction/pull/29
- If tflint's fix is false, code isn't fixed https://github.com/suzuki-shunsuke/test-tfaction/pull/30

feat(test-module): support tflint --fix

---

.github/workflows/main.yaml
.github/workflows/release.yaml
.github/workflows/wc-create-pr-branch.yaml

https://github.com/suzuki-shunsuke/release-js-action/releases/tag/v0.1.4

chore: update actions

---

create-follow-up-pr/create_commit.sh
create-follow-up-pr/main.sh
create-follow-up-pr/skip_create_pr.sh
terraform-apply/download_plan_file.sh
terraform-apply/main.sh
terraform-docs/terraform-docs.sh
terraform-plan/main.sh
terraform-plan/renovate_change.sh
tfmigrate-apply/main.sh
tfmigrate-plan/main.sh
update-drift-issue/post-comment.sh

```yaml
env:
TFACTION_DEBUG: "true"
```

feat: support debug mode

---

create-follow-up-pr/github-comment.yaml
create-follow-up-pr/main.sh

fix: add mentions if terraform apply fails

---

.github/workflows/autofix.yaml
.gitignore
cmdx.yaml
js/package-lock.json
js/package.json
js/src/index.ts
js/src/lib/index.ts
js/src/test-action/index.ts
js/test/tfaction-root.yaml
schema/tfaction-root.json
schema/tfaction.json
setup/test/opentofu/foo/.terraform.lock.hcl
setup/test/terragrunt/foo/.terraform.lock.hcl

chore: generate JSON Schema from Zod

---

scaffold-tfmigrate/action.yaml

- https://github.com/suzuki-shunsuke/tfaction/issues/2642

feat: support scaffolding tfmigrate by securefix action

---

generate-config-out/action.yaml
generate-config-out/aqua-checksums.json

- https://github.com/suzuki-shunsuke/tfaction/issues/2642

feat: import resources by securefix action

---

plan/action.yaml
tfmigrate-plan/action.yaml
tfmigrate-plan/main.sh

- https://github.com/suzuki-shunsuke/tfaction/issues/2642

feat: support creating .tfmigrate.hcl by securefix action

---

create-follow-up-pr/action.yaml
create-follow-up-pr/create_commit.sh
create-follow-up-pr/create_group_label.sh
create-follow-up-pr/main.sh
create-follow-up-pr/skip_create_pr.sh
create-scaffold-module-pr/action.yaml
create-scaffold-pr/action.yaml
js/src/get-follow-up-pr-param/index.ts
js/src/run.ts
scaffold-tfmigrate/action.yaml

- https://github.com/suzuki-shunsuke/tfaction/issues/2642

feat: support creating follow up prs by securefix action
