docs/config.md, list-targets-with-changed-files/dist/index.js, list-targets-with-changed-files/src/index.ts
e.g.
AS IS: `github/foo`
TO BE: `{target: 'github/foo', runs_on: 'ubuntu-latest'}`
```yaml
tfmigrate:
name: "tfmigrate (${{matrix.target.target}})" # CHANGED
runs-on: ${{matrix.target.runs_on}} # CHANGED
needs: setup
if: "join(fromJSON(needs.setup.outputs.tfmigrate_targets), '') != ''"
strategy:
fail-fast: false
matrix:
target: ${{fromJSON(needs.setup.outputs.tfmigrate_targets)}}
env:
TFACTION_TARGET: ${{matrix.target.target}} # CHANGED
terraform:
name: "terraform (${{matrix.target.target}})" # CHANGED
runs-on: ${{matrix.target.runs_on}} # CHANGED
needs: setup
if: "join(fromJSON(needs.setup.outputs.terraform_targets), '') != ''"
strategy:
fail-fast: false
matrix:
target: ${{fromJSON(needs.setup.outputs.terraform_targets)}}
env:
TFACTION_TARGET: ${{matrix.target.target}} # CHANGED
```
This …
=> feat: support configuring `runs_on`

docs/config.md, export-secrets/dist/index.js, export-secrets/src/lib.ts
BREAKING CHANGE: the structure of `secrets` is changed
AS IS
```yaml
secrets:
<environment variable name>: <secret name>
```
TO BE
```yaml
secrets:
- env_name: <environment variable name>
secret_name: <secret name>
```
=> feat(export-secrets): change configuration structure of GitHub Secrets

create-follow-up-pr/main.sh, list-targets-with-changed-files/dist/LICENSE, list-targets-with-changed-files/dist/index.js, list-targets-with-changed-files/package-lock.json, list-targets-with-changed-files/package.json, list-targets-with-changed-files/src/index.ts
Close #117 
Instead of adding `target` label to the follow up pull request,
`create-follow-up-pr` action embeds HTML comment `` into the head of the follow up pull request body.
`list-targets` action checks the HTML comment.
=> fix: fix create-follow-up-pr

scaffold-working-dir/action.yaml
Fix the error.
```
Run suzuki-shunsuke/tfaction/get-target-config@v0.4.0
env:
GITHUB_TOKEN: ***
TFACTION_TARGET: gcp/suzuki-shunsuke-test-1
Error: "environment variable TFACTION_JOB_TYPE is required"
```
=> fix(scaffold-working-dir): set TFACTION_JOB_TYPE

terraform-apply/action.yaml, terraform-plan/action.yaml, tfmigrate-plan/action.yaml
https://github.com/aws/aws-cli/issues/5262#issuecomment-705832151
It failed to run `aws s3 cp` because the region isn't specified.
=> fix: specify AWS_DEFAULT_REGION

create-follow-up-pr/main.sh
Follow up #179 
Mention is duplicated if pull request author and GITHUB_ACTOR are same.
=> fix: fix duplicated mention

scaffold-working-dir/action.yaml
AS IS
```
aqua.yaml
aqua/
tflint.yaml
tfsec.yaml
conftest.yaml
terraform.yaml
```
TO BE
```
aqua.yaml
```
Currently, there is no reason to separate files per package.
And to update tflint and tflint plugin together by Renovate grouping feature,
tflint version should be managed in the same directory with tflint plugin.
=> fix: remove the directory "aqua" on the working directory

terraform-apply/main.sh
Since v0.5.13 apply workflow failed with the following message in GCS:
> run a command: exec: "-config": executable file not found in $PATH
I fixed to move `--` flag in terraform-apply workflow.
=> Fix GCS apply comment

tfmigrate-apply/main.sh
We got the following error on applying tfmigrate:
```
...
Run suzuki-shunsuke/tfaction/tfmigrate-apply@v0.5.14
Run suzuki-shunsuke/tfaction/get-target-config@v0.5.14
Run bash /home/runner/work/_actions/suzuki-shunsuke/tfaction/v0.5.14/tfmigrate-apply/main.sh
/home/runner/work/_actions/suzuki-shunsuke/tfaction/v0.5.14/tfmigrate-apply/main.sh: line 7: TFACION_TARGET: unbound variable
Error: Process completed with exit code 1.
```
I noticed `TFACION_TARGET` is not set. Instead `TFACTION_TARGET` is set.
Fix the typo.
Thanks.
=> Fix typo of `$TFACTION_TARGET`

tfmigrate-plan/github-comment.yaml, tfmigrate-plan/main.sh
Close #511
#511 #516 tfmigrate-plan: Support testing with Conftest
In the job `tfmigrate-plan`, `conftest test` wasn't run so violated change could be missed.
This pull request fixes `tfmigrate-plan` to run `contest test` after running `tfmigrate plan`.
For this change, we use `tfmigrate plan`'s `--out` option.
This option was deprecated, but the deprecation was reverted.
- https://github.com/minamijoyo/tfmigrate/issues/106#issuecomment-1246495788
So there is no problem to use this option.
It works. 👍 
This screenshot shows the case that `tfmigrate plan` passed but `contest test` failed.
=> feat(tfmigrate-plan): support testing with Conftest

renovate.json
* https://docs.renovatebot.com/configuration-options/#ignorepaths
* https://docs.renovatebot.com/presets-config/#configbase
=> chore: stop using `config:base` preset because it ignores `test` directory

get-global-config/dist/index.js, get-global-config/src/index.ts, scaffold-working-dir/action.yaml
By default scaffold-working-directory creates `aqua.yaml` and add some packages.
```sh
aqua init
aqua g -i open-policy-agent/conftest terraform-linters/tflint aquasecurity/tfsec hashicorp/terraform
```
You can skip this.
```yaml
scaffold_working_directory:
skip_adding_aqua_packages: true
```
You can configure packages and their versions in your template or you can also manage them in repository root's aqua.yaml.
=> feat(scaffold-working-directory): support skipping to add aqua packages

test/action.yaml, test/github-comment.yaml
Hi, @suzuki-shunsuke 
I added header for `terraform validate` comment.
before
after
refer to tfmigrate template
https://github.com/suzuki-shunsuke/tfaction/blob/main/tfmigrate-plan/github-comment.yaml
=> fix: added header for `terraform validate` comment

test/action.yaml
- https://github.com/suzuki-shunsuke/github-action-tfsec/pull/612
- https://github.com/aquasecurity/tfsec/issues/2070#issuecomment-1669056215
=> fix(test): enable tfsec's `--ignore-hcl-errors` to support Terraform's import block

get-target-config/action.yaml, get-target-config/dist/index.js, get-target-config/src/index.ts, get-target-config/src/lib.ts, test/action.yaml
- https://github.com/suzuki-shunsuke/tfaction/discussions/957
- https://github.com/aquasecurity/tfsec/discussions/1994
- https://github.com/aquasecurity/tfsec/blob/master/docs/index.md#-tfsec-to-trivy-migration
Update `test` action to support running `trivy config` command.
You can run trivy instead of tfsec.
This pull request doesn't change the default behaviour, which means by default tfsec is run and trivy isn't run.
To run trivy instead of tfsec, you need to set up following to the below.
trivy is run with [suzuki-shunsuke/trivy-config-action](https://github.com/suzuki-shunsuke/trivy-config-action).
--
1. Add `aquasecurity/trivy` to aqua.yaml
```sh
$ aqua g -i aquasecurity/trivy
```
2. Update `tfaction-root.yaml` to enable `trivy` and disable `tfsec`
```yaml
tfsec: …
```
=> feat: support trivy

test-module/action.yaml
Hi, I faced an error on `tfaction/test-module` action.
The bug is appeared  in v0.6.4, but the actual behavior seems to be broken for a long time.
Since `ghcp` uses `GITHUB_TOKEN` environment variable implicitly, we don't need to pass via `--token` argument.
See https://github.com/int128/ghcp#getting-started .
Ref:
- https://github.com/suzuki-shunsuke/tfaction/pull/1110
=> fix(test-module): Fix ghcp argument to use implicitly GITHUB_TOKEN

get-global-config/action.yaml, get-global-config/dist/index.js, get-global-config/src/index.ts, setup/action.yaml
- https://github.com/suzuki-shunsuke/tfaction-docs/pull/128
Support updating `aqua-checksums.json` by [aquaproj/update-checksum-action](https://github.com/aquaproj/update-checksum-action).
By default, this feature is disabled.
To enable it, please configure it in `tfaction-root.yaml`.
```yaml
aqua:
update_checksum:
enabled: true # default is false
skip_push: false # default is false
prune: true # default is false
```
=> feat(setup): update aqua-checksums.json

test-module/action.yaml
`terraform validate` may fail even if modules are valid
=> fix(test-module): stop running `terraform validate`

apply/action.yaml, list-targets-with-changed-files/action.yaml, list-targets-with-changed-files/dist/index.js, list-targets-with-changed-files/src/index.ts, list-targets/action.yaml, plan/action.yaml
Close #223
Added new actions `plan` and `apply`.
You can replace actions `terraform-plan` and `tfmigrate-plan` with `plan`, and can replace `terraform-apply` and `tfmigrate-apply` with `apply`.
You can merge jobs for `tfmigrate` with jobs for `terraform`.
You can simplify workflows.
This pull request keeps the compatibility.
1. Fix outputs of `setup` job
1. Remove jobs for tfmigrate
1. (Optional) Rename jobs `terraform-plan` and `terraform-apply` to `plan` and `apply`
1. Fix `TFACTION_JOB_TYPE`
1. Replace actions `terraform-plan` and `terraform-apply` with `plan` and `apply`
Before
```yaml
outputs:
tfmigrate_targets: ${{ steps.list-targets.outputs.tfmigrate_targets }}
terraform_targets: ${{ steps.list-targets.outputs.terraform_targets }}
```
```yaml
matrix:
target: …
```
=> feat: support merging jobs for tfmigrate and terraform

create-scaffold-module-pr/action.yaml, scaffold-module/action.yaml, test-module/action.yaml
Actions `scaffold-module`, `create-scaffold-module-pr`, `test-module` are changed.
1. Templates for Terraform Modules are required.
2. Stop running `terraform init` in `test-module` action
Users can customize templates of Terraform Modules.
The action `scaffold-module` is changed.
- Remove the input `module_path`
- Add mandatory environment variables `TFACTION_MODULE_PATH` and `TFACTION_MODULE_TEMPLATE_DIR`
- Templates for scaffolding Terraform Modules are required
- Remove the input `module_path`
- Set environment variables `TFACTION_MODULE_PATH` and `TFACTION_MODULE_TEMPLATE_DIR`
- Add templates for scaffolding Terraform Modules
Before
```yaml
on:
workflow_dispatch:
inputs:
module_path:
description: 'module path'
required: true
jobs:
scaffold:
steps:
- uses: …
```
=> feat(scaffold-module): require module templates

README.md
Hi, I’m @nari-ex from Topotal, Inc.
Thank you for your continuous great products as always. I was testing 1.0.0-2 today :v:
We forgot to add a comma and period when adding our company name to the who-uses list the other day.
So I would appreciate it if you could correct the company name.
If there are any other corrections, I would appreciate it if you could let me know.
=> docs: Fix topotal company name on who-uses-tfaction

terraform-apply/download_plan_file.sh
This pr fixes a bug `the template invalid-workflow-sha isn't found`.
=> fix(apply): specify github-comment config

check-terraform-skip/jest.config.js, check-terraform-skip/package-lock.json, check-terraform-skip/package.json, check-terraform-skip/vitest.config.mjs, get-global-config/jest.config.js, get-global-config/package-lock.json, get-global-config/package.json, get-global-config/vitest.config.mjs, get-target-config/jest.config.js, get-target-config/package-lock.json, get-target-config/package.json, get-target-config/vitest.config.mjs, list-changed-modules/jest.config.js, list-changed-modules/package-lock.json, list-changed-modules/package.json, list-changed-modules/vitest.config.mjs, list-module-callers/jest.config.js, list-module-callers/package-lock.json, list-module-callers/package.json, list-module-callers/vitest.config.mjs, list-targets-with-changed-files/jest.config.js, list-targets-with-changed-files/package-lock.json, list-targets-with-changed-files/package.json, list-targets-with-changed-files/vitest.config.mjs
Closes #1591
After this PR, `@jest/schemas` dependency remains in `package-lock.json`.
This is because Vitest's snapshot mechanism (Jest has it too) depends on [pretty-format](https://www.npmjs.com/package/pretty-format) that depends on [@jest/schemas](https://www.npmjs.com/package/@jest/schemas).
The below numbers are collected in `get-global-config` directory.
```
❯ npm run test
> test
> jest
PASS  src/run.test.ts
✓ default (2 ms)
✓ plan_workflow_name is required (13 ms)
✓ customize (1 ms)
Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        2.024 s
Ran all test suites.
```
```
❯ npm run test
> test
> vitest --run
RUN  v1.4.0 /Users/exoego/IdeaProjects/tfaction/get-global-config
✓ src/run.test.ts (3)
✓ default
✓ plan_workflow_name is required
✓ …
```
=> Migrate to vitest

export-secrets/dist/index.js, export-secrets/src/index.ts
This pull request updates the action `export-secrets` and outputs secret names passed to the action for troubleshooting.
The log is useful to check if secrets are passed to the action properly.
If secrets aren't passed properly, this isn't a bug of tfaction.
You have to check your workflow and the usage of tfaction.
- https://github.com/suzuki-shunsuke/tfaction/issues/1564
=> fix(export-secrets): output secret names for troubleshooting

check-terraform-skip/dist/index.js, export-aws-secrets-manager/dist/index.js, get-global-config/dist/index.js, get-target-config/action.yaml, get-target-config/dist/index.js, get-target-config/src/run.ts, lib/dist/index.d.ts, lib/dist/index.js, lib/src/index.ts, list-targets-with-changed-files/dist/index.js, schema/tfaction-root.json, schema/tfaction.json, setup/action.yaml
- https://github.com/suzuki-shunsuke/tfaction/discussions/1325
- https://github.com/google-github-actions/auth
This pull request adds the setting `gcp_access_token_scopes` to enable tfaction to set `google-github-actions/auth`'s `access_token_scopes`.
The format is same with `google-github-actions/auth`'s `access_token_scopes`.
e.g.
```yaml
targets:
- working_directory: gcp/
target: gcp/
terraform_plan_config:
gcp_access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/apps.groups.settings, https://www.googleapis.com/auth/admin.directory.group'
```
tfaction.yaml
```yaml
terraform_plan_config:
gcp_access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform, …
```
=> feat(setup): support setting `google-github-actions/auth`'s `access_token_scopes`

list-targets-with-changed-files/dist/index.js, list-targets-with-changed-files/src/run.ts
It has been found that `\r\n` instead of `\n` is sometimes used as a line break code in prBody. If `\r\n` is used as a newline code, the detected target will contain extra spaces at the end.
- Link to the issue: https://github.com/suzuki-shunsuke/tfaction/issues/1661
=> trim trailing whitespace in follow-up comments

list-targets-with-changed-files/dist/index.js, list-targets-with-changed-files/src/run.test.ts, list-targets-with-changed-files/src/run.ts
- https://github.com/suzuki-shunsuke/tfaction/pull/1660 is improved the problem but still there like adding lines before comment or update the comment line.
- Use regexp to handle follow up pr target for robustness
- I think using PR label or something is robuster than using PR body string but I don't know well about tfaction
- Link to the issue: https://github.com/suzuki-shunsuke/tfaction/issues/1661
=> fix: use regexp to handle follow up pr target

check-terraform-skip/dist/index.js, create-follow-up-pr/action.yaml, export-aws-secrets-manager/dist/index.js, export-secrets/src/lib.ts, get-global-config/dist/index.js, get-target-config/dist/index.js, lib/dist/index.d.ts, lib/dist/index.js, lib/src/index.ts, list-targets-with-changed-files/dist/index.js, list-targets-with-changed-files/src/run.ts, scaffold-tfmigrate/action.yaml, scaffold-working-dir/action.yaml, schema/tfaction-root.json, setup/action.yaml, terraform-apply/action.yaml, terraform-plan/action.yaml, test-module/action.yaml, test/action.yaml, tfmigrate-apply/action.yaml, tfmigrate-plan/action.yaml, update-drift-issue/action.yaml
- [X ] Read [CONTRIBUTING.md](https://github.com/suzuki-shunsuke/tfaction/blob/main/CONTRIBUTING.md)
- [X ] Read [OSS Contribution Guide](https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/README.md)
- [X ] [Write a GitHub Issue before creating a Pull Request](https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/README.md#create-an-issue-before-creating-a-pull-request)
- Link to the issue: https://github.com/suzuki-shunsuke/tfaction/issues/1738
- [X ] [All commits are signed](https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/docs/commit-signing.md)
- [X ] [Avoid force push](https://github.com/suzuki-shunsuke/oss-contribution-guide?tab=readme-ov-file#dont-do-fo …
=> feat(runs_on): permit using array of string to select specific runner

conftest/dist/index.js, conftest/src/run.ts, lib/dist/index.d.ts, lib/dist/index.js, lib/src/index.ts
- https://github.com/suzuki-shunsuke/tfaction/pull/1893
```yaml
conftest:
policies:
- policy: policy/tfaction
paths:
- tfaction.yaml # glob is available https://www.npmjs.com/package/glob
```
glob is available.
https://www.npmjs.com/package/glob
=> feat: support running conftest on given globs

conftest/package-lock.json, conftest/package.json, conftest/src/run.ts
- https://github.com/suzuki-shunsuke/tfaction/issues/1896#issuecomment-2412399621
You can now refer `target` and `working_directory` in Conftest policies via [--data option](https://www.conftest.dev/options/#-data).
tfaction creates a special data file temporarily and pass it to your policies.
```rego
import data.tfaction
target := tfaction.target
working_directory := tfaction.working_directory
```
=> feat(conftest): create a special data file

get-target-config/src/run.test.ts, get-target-config/src/run.ts, lib/src/index.ts, setup/action.yaml
- Link to the issue: https://github.com/suzuki-shunsuke/tfaction/issues/1930
[aws-actions/configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) to allow [role-session-name](https://github.com/aws-actions/configure-aws-credentials/blob/2cefa29f8797029f898b1baeff3e21a144128687/action.yml#L49-L51) to be set when execution AssumeRole.
Currently, tfaction has a fixed value of `samplerolesession` when execute AssumeRole operation, which is undesirable.
https://github.com/suzuki-shunsuke/tfaction/blob/1f76ed16ff681ff5bff6feaa117f97a39d0b5808/setup/action.yaml#L93
This value is mainly recorded in CloudTrail as the User name. 
Ideally, different names should be set for different IAM …
=> feat: added `aws_role_sesion_name`

.github/workflows/test.yaml, .github/workflows/wc-update-aqua-checksums-install.yaml, aqua-checksums.json, install/action.yaml, install/aqua-checksums.json, install/aqua.yaml, install/aqua/ci-info.yaml, install/aqua/conftest.yaml, install/aqua/gh.yaml, install/aqua/ghcp.yaml, install/aqua/github-comment.yaml, install/aqua/terraform-config-inspect.yaml, install/aqua/terraform-docs.yaml, install/aqua/tfaction-go.yaml, install/aqua/tfcmt.yaml, install/aqua/tfmigrate.yaml, list-targets/action.yaml, setup/action.yaml
`setup` and `list-targets` actions install the following tools via aqua and `AQUA_GLOBAL_CONFIG`.
- ci-info
- conftest
- gh
- ghcp
- github-comment
- terraform-config-inspect
- terraform-docs
- tfaction-go
- tfcmt
- tfmigrate
tfaction install these tools securely via checksum verification.
So you don't need to install these tools yourself anymore, but you can still overwrite these commands by your own aqua.yaml because your own aqua.yaml takes precedence over `$AQUA_GLOBAL_CONFIG`.
On the other hand, you still have to install the following tools yourself.
- tfsec
- tflint
- trivy
- Terraform
And if you want to hide old comments, you still have to install and run github-comment yourself.
=> feat: install dependencies

README.md
Hi,
We are using tfaction to automate our terraform workflows. We would be happy if you could add us to the who-uses-tfaction list. I've also included a link to our blog post about it.
- Link to the issue:
=> docs: add newmo to who-uses-tfaction

get-target-config/src/run.ts
tflint --fix requires tflint v0.48.0 or later.
So this is a breaking change.
To keep the compatibility, we disable this feature by default.
You can enable this feature by tfaction-root.yaml
```yaml
tflint:
enabled: true
fix: true
```
=> fix(test): disable tflint --fix by default

.github/workflows/release.yaml, ghalint.yaml
https://github.com/suzuki-shunsuke/tfaction/actions/runs/12490571831/job/34855465121
```
Run git push origin "$TAG"
fatal: could not read Username for 'https://github.com/': No such device or address
```
=> ci: enable persist-credentials for release

js/action.yaml
- Link to the issue:
Hi @suzuki-shunsuke
In tfaction v1.13.4, the following warning appeared when using export-secrets in tfaction/js.
```
Warning: Unexpected input(s) 'secrets', valid inputs are ['action', 'labels', 'skip_label_prefix', 'pr_author', 'changed_files', 'config_files', 'config', 'module_files', 'pull_request', 'module_callers', 'plan', 'github_token']
```
Probably, this is because TypeScript refers to inputs that are not defined in `action.yaml`
https://github.com/suzuki-shunsuke/tfaction/blob/952fc2e30a83ae774f0218486e86b6d71b0adb53/js/src/export-secrets/index.ts#L50
=> chore: added `secrets` input to tfaction/js

aqua-checksums.json, aqua/terraform.yaml, js/src/list-module-callers/index.ts
Fix a bug list-targets fails if `terragrunt.hcl` exists in the repository but terragrunt and terraform aren't found in the repository root directory.
=> fix: run terragrunt render-json on the directory where terragrunt.hcl exists

setup/action.yaml
Closes https://github.com/suzuki-shunsuke/tfaction/issues/2330
~This issue introduces a new flag in the setup action that enables users to choose whether to skip the execution of the `google-github-actions/setup-gcloud` step.~
After reviewing, I removed the setup-gcloud step because it was unnecessary.
- Link to the issue: https://github.com/suzuki-shunsuke/tfaction/issues/2330
=> clean(deps): remove unused `setup-gcloud` step

generate-config-out/action.yaml, scaffold-working-dir/action.yaml
Close #2918
get-target-config doesn't output `target`.
Instead, it sets the environment variable `TFACTION_TARGET`.
- https://github.com/suzuki-shunsuke/tfaction/commit/cac6c53bba43bbf419863f6b151183ae41fc408d
- https://github.com/suzuki-shunsuke/tfaction/pull/2785
- https://github.com/suzuki-shunsuke/tfaction/commit/b811fe329dce029a2d4d95f3b4302c493a32b9df
=> fix: fix a bug that TFACTION_TARGET is empty

js/src/get-follow-up-pr-param/index.ts
- Add assignees from the original PR to follow-up PRs automatically
- Implement zod validation for pr.json parsing
- Resolves #2946
- Read assignees from `$CI_INFO_TEMP_DIR/pr.json`
- Add zod schema validation for type safety
- Include original PR assignees in addition to PR author and actor
=> feat: add assignees of the original PR to follow-up PRs
